
runport: ":8998"
dominname: "http://xxx.com"
envmode: "dev"
projectpath: "/usr/local/workspace/src/readbook"
wxappid: "xxx"
wxsecret: "xx"
wxpaymchid: "xx"
wxpaykey: "xxxx"
wxpushtemplate:
  - "0,Q4DW2x0UY_xzJF4LOvpMHYj1fzKD_g,http://xxx/task.html"
  - "1,w4DW2x0UY_xzJF4LOdMHYj1fzKD_g,http://xxx/task.html"
wxtoken: "xxx"

logproject: "APILOC"
logpath: "./logs"
loglevel: "debug"
logMaxSize: 268435456
logBuffSize: 1048576
logHook: 
  - "file"
emailHost: "smtp.exmail.qq.com"
emailPort: 25
emailFrom: ""
emailTo: ""
emailPassword: ""
emailAlias: "readbook"
exceptionTimeout: 600